apiVersion: batch/v1
kind: Job
metadata:
  name: n8n-backup-test-simple
  namespace: n8n
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: backup
        image: postgres:17
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        command:
        - /bin/bash
        - -c
        - |
          echo "🚀 Testando backup do n8n..."
          
          # Testar conectividade
          pg_isready -h $PG_HOST -U $PG_USER -d $PG_DATABASE
          if [ $? -eq 0 ]; then
            echo "✅ Conectividade OK"
          else
            echo "❌ ERRO: Não foi possível conectar ao PostgreSQL"
            exit 1
          fi
          
          # Testar backup simples
          echo "📦 Iniciando backup de teste..."
          pg_dump -h $PG_HOST -U $PG_USER -d $PG_DATABASE --schema-only > /backup/test-schema.sql
          
          if [ -f /backup/test-schema.sql ]; then
            echo "✅ Backup de teste criado com sucesso"
            ls -lah /backup/test-schema.sql
          else
            echo "❌ ERRO: Backup de teste não foi criado"
            exit 1
          fi
          
          echo "✅ Teste de backup concluído com sucesso!"
        env:
        - name: PG_HOST
          value: "172.23.64.3"
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_NON_ROOT_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_NON_ROOT_PASSWORD
        - name: PG_DATABASE
          value: "n8n-postgres-db"
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_NON_ROOT_PASSWORD
        volumeMounts:
        - name: backup-storage
          mountPath: /backup
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: n8n-backup-claim
      restartPolicy: Never
