apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: n8n-metrics
  namespace: n8n
  labels:
    app: n8n
spec:
  selector:
    matchLabels:
      service: n8n
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
