apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-service-account
  namespace: n8n
automountServiceAccountToken: false  # Segurança extra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: n8n-role
  namespace: n8n
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: n8n-role-binding
  namespace: n8n
subjects:
- kind: ServiceAccount
  name: n8n-service-account
  namespace: n8n
roleRef:
  kind: Role
  name: n8n-role
  apiGroup: rbac.authorization.k8s.io