apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
  namespace: n8n
spec:
  replicas: 3
  selector:
    matchLabels:
      app: n8n-worker
  template:
    metadata:
      labels:
        app: n8n-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: worker
        image: docker.n8n.io/n8nio/n8n:1.107.3
        command: ["n8n"]
        args: ["worker"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
          value: "true"
        - name: N8N_RUNNERS_ENABLED
          value: "true"
        - name: OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS
          value: "true"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: redis-auth
        - name: NODE_OPTIONS
          value: --max-old-space-size=3072 --expose-gc
        - name: NODE_ENV
          value: production
        - name: V8_FORCE_GC
          value: "1"
        - name: N8N_EXECUTION_TIMEOUT
          value: "7200"
        - name: N8N_EXECUTE_IN_PROCESS
          value: "false"
        - name: EXECUTIONS_DATA_PRUNE
          value: "true"
        - name: EXECUTIONS_DATA_MAX_AGE
          value: "1"
        - name: EXECUTIONS_MODE
          value: queue
        - name: QUEUE_BULL_REDIS_HOST
          value: redis-master.n8n.svc.cluster.local
        - name: QUEUE_BULL_REDIS_PORT
          value: "6379"
        - name: QUEUE_BULL_REDIS_DB
          value: "0"
        - name: QUEUE_BULL_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: redis-auth
        - name: N8N_REDIS_HOST
          value: redis-master.n8n.svc.cluster.local
        - name: N8N_REDIS_PORT
          value: "6379"
        - name: N8N_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: redis-auth
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: N8N_ENCRYPTION_KEY
              name: n8n-encryption
        - name: DB_TYPE
          value: postgresdb
        - name: DB_POSTGRESDB_HOST
          value: 172.23.64.3
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        - name: DB_POSTGRESDB_DATABASE
          value: n8n-postgres-db
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_NON_ROOT_USER
              name: postgres-secret
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_NON_ROOT_PASSWORD
              name: postgres-secret
        - name: DB_POSTGRESDB_CONNECTION_TIMEOUT
          value: "120000"
        - name: DB_POSTGRESDB_POOL_SIZE
          value: "2"
        - name: DB_POSTGRESDB_IDLE_CONNECTION_TIMEOUT
          value: "60000"
        - name: N8N_PROTOCOL
          value: https
        - name: N8N_HOST
          value: n8n-logcomex.34-8-101-220.nip.io
        - name: N8N_WEBHOOK_URL
          value: https://n8n-logcomex.34-8-101-220.nip.io
        - name: N8N_EDITOR_BASE_URL
          value: https://n8n-logcomex.34-8-101-220.nip.io
        - name: WEBHOOK_URL
          value: https://n8n-logcomex.34-8-101-220.nip.io
        - name: N8N_PUSH_BACKEND
          value: websocket
        - name: N8N_LISTEN_ADDRESS
          value: 0.0.0.0
        - name: N8N_PUSH_BACKEND_WEBSOCKET_HEARTBEAT_INTERVAL
          value: "30000"
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        # Workers não precisam de volume persistente
      volumes:
      - name: n8n-secret
        secret:
          defaultMode: 420
          secretName: n8n-secret
      - name: postgres-secret
        secret:
          defaultMode: 420
          secretName: postgres-secret
