apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring-new
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    name: web
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: monitoring-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
